### ISSUE TITLE
document_type / localized_name always calls `@localizer`, even if `!block_given?` 

### ISSUE THREAD

**Issue by florianeck** [kentaroi/elasticsearch-model-globalize#5]
I faced an issue which causes my document_type always to be equivalent to the index name. The Setup is the following:

```
# initializer
# Tell Elasticsearch which indices it should use for the locales
Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name do |name, locale|
  ProductsIndexing.index_name(locale) # => method that returns the name of the index
end
```

then in `Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name` the following happens:
(I rewrote the method a little bit for debugging reasons)

```
def self.localized_name(name=nil, locale=nil, &block)
  @localizer = block if block_given? # gets set to Proc.new { ProductsIndexing.index_name(locale) }
  result = @localizer ? @localizer.call(name, locale) : "#{name}-#{locale}"
  puts "#{[name, locale, block_given?].inspect} -> #{result}"

  # when method gets called from 'one_index_per_language.rb#73' (.document_type)
  # no block is given but the output from puts is the following:
  # ["material", :fr, false] -> makerist-development-products-fr
  # expected output
  # 'material-fr'
  return result
end
```

In the end, i have document_types in the index that are called the same as the index, with wrong mapping of course.

i created a PR with a possible solution, but still I'd love to know the intention to use an instance variable there.

**Comment by kentaroi** [comment]
Hi, @florianeck.

Thanks for opening an issue :smile: 

Because I created this gem almost two years ago and have not updated it for a long time, I'm sorry I do not understand the issue completely.

How about setting `document_type_base` with `document_type_base=` class method?

The intention to use an instance variable there is this gem expects that a gem user initializes his/her localizing rule in `config/initializers/elasticsearch-model-globalize.rb`, and the gem will use the rule from the whole gem.

Calling `Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name` method without block in `document_type` method means `document_type` method uses user defined rule with arguments, `document_type_base` and `::Globalize.locale`.

I am not good at English and I suspect I misunderstand the issue.
Please ask me if you have any question.

**Comment by kentaroi** [comment]
Any comments?

To clarify, I will write some more.

If you want to define localizing rule, you should call `Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name` with block.
If you want to use the rule, you should call `Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name` without block.

Therefore, you should use `Elasticsearch::Model::Globalize::OneIndexPerLanguage.localized_name` with block in `config/initializers/elasticsearch-model-globalize.rb`.

The gem does not call the method with block because the gem does not want to write a rule, but use a rule which user defined.

To define document_type correctly, you should call a class method `document_type_base` with argument or another class method `document_type_base=`.

Thank you.
